/**
 * Hand-picked, individually verified GetYourGuide products — the network's
 * "direct sales items". Each row deep-links to ONE bookable activity page, so
 * the visitor lands on a Check-availability button instead of a search listing.
 *
 * ── Where these come from ──────────────────────────────────────────────────
 * Selected out of `shared/gyg/catalog.md` (839 products, generated by
 * `scripts/gyg-catalog.mjs`) and then opened one by one in a real browser on
 * 2026-07-29. Every row below returned HTTP 200, did NOT redirect, carried the
 * title stated here, and rendered a booking CTA.
 *
 * 🔴 NEVER add a row by guessing or hand-editing a path. A wrong id does not
 * 404 — it silently serves a real page somewhere else in the world. Measured on
 * 2026-07-29: `rovaniemi-l1155` renders Eisenstadt (Austria), `lapland-l4404`
 * renders Parc des Princes (Paris), and a guessed Korouoma id redirected to
 * Angra do Heroísmo (Azores). All three answered 200 with a valid-looking page.
 * Take the path from the catalogue, then open it before shipping.
 *
 * ── Price: shown, but always dated and attributed ─────────────────────────
 * `price` is GetYourGuide's own "from" price as it stood on GYG_PRICE_AS_OF —
 * it is NOT our price and must never be rendered as one. Every card prints the
 * source and the date next to it, so a visitor who finds a different number at
 * checkout can see why.
 *
 * Currency is EUROS. An earlier comment here claimed USD; that was wrong. All
 * 839 catalogue values begin with `€` — the USD figure lives in a product
 * page's JSON-LD (`priceCurrency: "USD"`), a different field from the visible
 * token the crawler stores. Counted 2026-07-30.
 *
 * Still deliberately absent: ratings and review counts. We have no way to keep
 * those current, and a stale "4.6 (869)" is a claim about other people's
 * experience rather than a fact about the product.
 *
 * ── Re-verification ───────────────────────────────────────────────────────
 * Activities get delisted. `lv-link-affiliate-audit-weekly` is the natural
 * place to re-check these paths; a dead row is a broken promise, not a warning.
 *
 * ── 🔴 Rivin poisto/uudelleennimeäminen rikkoo laplandgiftsin buildin ──────
 * laplandgifts/src/data/experiences.ts poimii rivejä näistä listoista
 * OTSIKKOFRAGMENTILLA (pick()-apuri, kaatuu keräysvaiheessa jos fragmentti
 * ei osu). Todistettu 2026-08-03: t505204:n poisto ACTIVITIES_PICKSistä
 * kaatoi giftsin buildin (korjattu giftsissä 98b3637). Ennen kuin poistat
 * tai uudelleennimeät rivin, greppaa otsikko myös laplandgiftsistä.
 */

export interface GygPick {
  /** GetYourGuide path: `<location-lNNN>/<slug-tNNN>`. No leading/trailing slash. */
  path: string;
  /** Title as GetYourGuide renders it, minus the "City: " prefix. */
  title: string;
  /** Destination shown to the visitor. */
  place: string;
  /**
   * GetYourGuide's "from" price on GYG_PRICE_AS_OF, euros, e.g. "188 €".
   * Optional: a row with no price in the catalogue renders without one rather
   * than with a guess. Never print this without the source and date beside it.
   */
  price?: string;
  /** Omitted when the source value was unreliable — never print a guess. */
  duration?: string;
  /**
   * Per-row override for the price's "as of" date. Set when a single row's
   * price was read on a DIFFERENT day than the catalogue crawl — the row then
   * renders its own date instead of GYG_PRICE_AS_OF, so neither date lies
   * about the other rows. (First use: christmas t434430, read 2026-08-01.)
   */
  priceAsOf?: string;
  /** Placement tag, snake_case, no domain. The Worker prefixes the site. */
  sid: string;
}

/**
 * The date the prices below were read off GetYourGuide. Rendered next to every
 * price, because an undated partner price is a promise we cannot keep — they
 * change it, not us. Re-run scripts/gyg-add-prices.mjs after a fresh crawl.
 */
export const GYG_PRICE_AS_OF = "2026-07-29";

const GO = "https://go.laplandvibes.com/go/activities";

/**
 * Affiliate href through the redirect Worker (LV rule: never a raw partner URL
 * in source). The Worker appends `partner_id` and resolves per-site attribution
 * from the Referer header. Verified end-to-end 2026-07-29.
 *
 * `lang` is handed to the WORKER as `language`. It is not passed through to
 * GetYourGuide — 🔴 `?language=xx` does nothing there, measured in a real
 * browser 2026-08-02: the product page renders identical English with and
 * without it. GetYourGuide localises by a `<lang>-<country>/` path prefix, and
 * resolves the product from its `-tNNNNN` id, so `handleGyg` turns this
 * parameter into that prefix.
 *
 * 🔴 Until 2026-08-02 the Worker's PASSTHROUGH list did not include `language`
 * at all, so this parameter was dropped on the floor and every site using
 * these picks sent its readers to the English page. Both halves of that bug
 * were invisible: the site looked like it was asking for a language, and the
 * parameter it asked with would not have worked anyway.
 */
export function gygHref(pick: GygPick, lang?: string, sidOverride?: string): string {
  // sidOverride: a pick's baked-in sid is named after the site the row was
  // originally curated for (hub_home_pick_*, kids_home_pick_*). A site reusing
  // the row keeps the Worker's domain prefix but reports revenue under another
  // site's placement name — measured on laplandgifts 2026-08-14, where GYG
  // income could not be attributed to any gifts page. Callers that reuse
  // another site's picks MUST pass their own sid; single-site callers omit it.
  const p = new URLSearchParams({ sid: sidOverride || pick.sid });
  // GYG's own language codes; en is their default and needs no parameter.
  const L: Record<string, string> = {
    fi: "fi", de: "de", ja: "ja", es: "es", "pt-BR": "pt-br",
    "zh-CN": "zh", ko: "ko", fr: "fr", it: "it", nl: "nl", sv: "sv",
  };
  const code = lang ? L[lang] : undefined;
  if (code) p.set("language", code);
  return `${GO}/${pick.path}?${p.toString()}`;
}

/** Family-bookable experiences for laplandkids.com. */
export const KIDS_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-reindeer-huskies-santa-claus-village-t301148",
    price: "188 €",
    title: "Reindeer, Huskies & Santa Claus Village",
    place: "Rovaniemi",
    // duration omitted on purpose: the source value was a sales badge
    // ("#1 selling day trip"), not a length. A badge is not a duration.
    sid: "kids_home_pick_reindeer_huskies_santa",
  },
  {
    path: "rovaniemi-l2653/entrance-ticket-to-snowman-world-in-santa-claus-village-t404948",
    price: "37 €",
    title: "Snowman World Entry Ticket in Santa Claus Village",
    place: "Rovaniemi",
    duration: "1 day",
    sid: "kids_home_pick_snowman_world",
  },
  {
    path: "saariselka-l181615/saariselka-husky-safari-with-kennel-visit-t853272",
    price: "249 €",
    title: "10 km Husky Safari with kennel visit",
    place: "Saariselkä",
    duration: "4 h",
    sid: "kids_home_pick_husky_kennel",
  },
  {
    path: "ruka-l192178/ruka-reindeer-ride-with-snacks-and-storytime-t1106609",
    price: "77 €",
    title: "Reindeer Ride with Snacks and Storytime",
    place: "Ruka",
    duration: "2 h",
    sid: "kids_home_pick_reindeer_storytime",
  },
];

/** Snowmobile tours for laplandsnowmobile.com. */
export const SNOWMOBILE_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-drive-new-2025-snowmobiles-on-arctic-safari-bbq-t699161",
    price: "119 €",
    title: "Drive New 2025 Snowmobiles on Arctic Safari",
    place: "Rovaniemi",
    duration: "3 h",
    sid: "snowmobile_home_pick_arctic_safari_2025",
  },
  {
    path: "sirkka-l139331/levi-forest-snowmobile-safari-t404689",
    price: "126 €",
    title: "Easy Snowmobile Safari into the Nature",
    place: "Levi",
    duration: "2 h",
    sid: "snowmobile_home_pick_levi_forest",
  },
  {
    path: "saariselka-l181615/saariselka-snowmobile-safari-on-tundra-with-bbq-t790865",
    price: "199 €",
    title: "Snowmobile Safari on Tundra",
    place: "Saariselkä",
    duration: "3,5 h",
    sid: "snowmobile_home_pick_tundra",
  },
  {
    path: "kilpisjarvi-l146340/kilpisjarvi-border-of-three-countries-snowmobile-safari-t788580",
    price: "150 €",
    title: "Border of Three Countries Snowmobile Safari",
    place: "Kilpisjärvi",
    duration: "3 h",
    sid: "snowmobile_home_pick_three_countries",
  },
];

/**
 * Network-wide picks for the hub front page. Deliberately four DIFFERENT kinds
 * of trip in four different destinations — the hub's job is to show the breadth
 * of Lapland, not to rank one activity four times.
 */
export const HUB_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/northern-lights-tour-guaranteed-viewing-unlimited-mileage-t492901",
    price: "198 €",
    title: "Northern Lights Tour with Guaranteed Sightings",
    place: "Rovaniemi",
    duration: "8 h",
    sid: "hub_home_pick_aurora_rovaniemi",
  },
  {
    path: "kemi-l98127/kemi-afternoon-icebreaker-sampo-cruise-and-ice-floating-t504004",
    price: "402 €",
    title: "Icebreaker Sampo Cruise with Ice Floating",
    place: "Kemi",
    duration: "6,5–7 h",
    sid: "hub_home_pick_icebreaker_sampo",
  },
  {
    path: "sirkka-l139331/levi-5-km-husky-sledding-ride-in-levi-t654057",
    price: "150 €",
    title: "5 km Husky Sledding Ride",
    place: "Levi",
    duration: "2 h",
    sid: "hub_home_pick_husky_levi",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-korouoma-canyon-frozen-waterfalls-hike-bbq-t495118",
    price: "139 €",
    title: "Korouoma Canyon Frozen Waterfalls Hike & BBQ",
    place: "Rovaniemi",
    duration: "7 h",
    sid: "hub_home_pick_korouoma",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Network rollout 2026-07-30. All 28 paths below were opened live before being
// written here, and the titles are GetYourGuide's OWN live titles — not the
// catalogue's. Two differed: the catalogue read "Kermikka about 15 km reindeer
// sleigh ride" where the live page says "Reindeer Sleigh Ride Tour in Snowy
// Forest", and "Levi winter wilderness husky reindeer safari combo" is actually
// "Levi: 3-in-1 Combo Husky, Reindeer & Snowmobile". Shipping the catalogue's
// wording would have promised a product name the operator does not use.
// ─────────────────────────────────────────────────────────────────────────────

/** laplandhuskysafaris-new */
export const HUSKY_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-santa-claus-village-husky-ride-t462526",
    price: "63 €",
    title: "Santa Claus Village Husky Ride",
    place: "Rovaniemi",
    duration: "30 min",
    sid: "husky_home_pick_santa_claus_village_husky_ride",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-apukka-husky-adventure-7km-self-driven-t331216",
    price: "219 €",
    title: "Apukka Husky Adventure 6km, self-driven",
    place: "Rovaniemi",
    duration: "3,5 h",
    sid: "husky_home_pick_apukka_husky_adventure_6km_self_driven",
  },
  {
    path: "sirkka-l139331/levi-self-drive-guided-husky-tour-t453311",
    price: "121 €",
    title: "Self-Drive Guided Husky Tour",
    place: "Levi",
    duration: "1 - 2 h",
    sid: "husky_home_pick_self_drive_guided_husky_tour",
  },
  {
    path: "sirkka-l139331/levi-arctic-combo-husky-reindeer-ride-t503967",
    price: "169 €",
    title: "Arctic Combo – Husky & Reindeer Ride",
    place: "Levi",
    duration: "2 h",
    sid: "husky_home_pick_arctic_combo_husky_reindeer_ride",
  },
];

/**
 * laplandactivities-new.
 *
 * 🔴 Neljä ERI lajia neljälle kortille — 2026-07-30 rollout laittoi tähän
 * kolme poroajelua ja Vesa huomasi (2026-08-03: "varattavissa tänään
 * osiossa on kolme poroajelua?"). Aktiviteettisivuston etusivun tehtävä on
 * sama kuin hubin: näyttää Lapin kirjo, ei rankata yhtä lajia neljästi.
 * t418396 ja t505204 (molemmat poroajeluja) korvattu revontulilla ja
 * jääkellunnalla — molemmat avattu selaimessa 2026-08-03 (200, ei
 * uudelleenohjausta tuotetasolla, varauspainike renderöityi, hinta ja
 * kesto luettu tuotesivulta samana päivänä → per-rivi priceAsOf).
 * Ei karhutuotteita: karhunkatselu kuuluu Bear Kuusamo -kumppanille.
 */
export const ACTIVITIES_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-reindeer-experience-with-sleigh-ride-t300556",
    price: "87 €",
    title: "Reindeer Experience with Sleigh Ride",
    place: "Rovaniemi",
    duration: "2,5 h",
    sid: "activities_home_pick_reindeer_experience_with_sleigh_ride",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-husky-reindeer-experience-with-snowmobile-ride-t320613",
    price: "198 €",
    title: "Husky & Reindeer Experience with Snowmobile Ride",
    place: "Rovaniemi",
    duration: "6 h",
    sid: "activities_home_pick_husky_reindeer_experience_with_snowmobil",
  },
  {
    // Sama tuotenimi kuin hubin Rovaniemi-poiminnalla (t492901) mutta eri
    // tuote: tämä on saman konseptin Levi-versio (Arctic GM Experiences OY).
    path: "kittila-l165074/levi-northern-lights-tour-with-guaranteed-sightings-t693623",
    price: "199 €",
    priceAsOf: "2026-08-03",
    title: "Northern Lights Tour with Guaranteed Sightings",
    place: "Levi",
    duration: "8 h",
    sid: "activities_home_pick_northern_lights_guaranteed_levi",
  },
  {
    // Live-otsikko toistaa nimen kolmesti (GYG:n oma databugi:
    // "Ylläs: Ylläsjärvi Ice-Floating Experience: Ylläsjärvi …" ×3) —
    // tähän kirjoitettu kertaalleen, mikä on ilmiselvä tarkoitettu nimi.
    path: "akaslompolo-l2931/ice-floating-experience-yllas-t97086",
    price: "132 €",
    priceAsOf: "2026-08-03",
    title: "Ylläsjärvi Ice-Floating Experience",
    place: "Ylläs",
    duration: "2,5 h",
    sid: "activities_home_pick_ice_floating_yllas",
  },
];

/** laplandtours-new */
export const TOURS_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-daytime-husky-safari-t437502",
    price: "189 €",
    title: "Daytime Husky Safari",
    place: "Rovaniemi",
    duration: "1,5 h",
    sid: "tours_home_pick_daytime_husky_safari",
  },
  {
    path: "sirkka-l139331/levi-snowmobile-northern-lights-hunting-trip-t407158",
    price: "159 €",
    title: "Snowmobile Northern Lights Hunting Trip",
    place: "Levi",
    duration: "3 h",
    sid: "tours_home_pick_snowmobile_northern_lights_hunting_trip",
  },
  {
    // 🔴 Replaced 2026-07-30. This slot held
    // `rovaniemi-icebreaker-arktis-cruise-with-ice-floating-t621594`, whose title
    // is byte-identical to the Kemi row below — two cards on the same page read
    // as the same tour listed twice, and the auto-generated `sid` truncated to
    // the same 55 characters so analytics could not tell them apart either.
    // Ranua keeps Rovaniemi represented with a genuinely different experience.
    // Verified live 2026-07-30: 200, no redirect, title as stated.
    path: "rovaniemi-l2653/rovaniemi-ranua-s-wildlife-park-ticket-with-transportation-t786889",
    price: "99 €",
    title: "Ranua’s Wildlife Park Ticket with Transportation",
    place: "Rovaniemi",
    duration: "8 h",
    sid: "tours_home_pick_ranua_wildlife_park",
  },
  {
    path: "kemi-l98127/kemi-icebreaker-arktis-cruise-with-ice-floating-t727384",
    price: "307 €",
    title: "Icebreaker Arktis Cruise with Ice Floating",
    place: "Kemi",
    duration: "6 h",
    sid: "tours_home_pick_icebreaker_arktis_kemi",
  },
];

/** laplandvisit */
export const VISIT_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-korouoma-canyon-frozen-waterfalls-tour-t349531",
    price: "145 €",
    title: "Korouoma Canyon and Frozen Waterfalls Tour",
    place: "From Rovaniemi",
    duration: "7 h",
    sid: "visit_home_pick_korouoma_canyon_and_frozen_waterfalls_to",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-winter-wonderland-in-riisitunturi-national-park-t439000",
    price: "190 €",
    title: "Riisitunturi National Park Day Trip with Lunch",
    place: "Rovaniemi",
    duration: "8 h",
    sid: "visit_home_pick_riisitunturi_national_park_day_trip_with",
  },
  {
    path: "saariselka-l181615/auroras-northern-lights-in-saariselka-t762238",
    price: "179 €",
    title: "Auroras Northern Lights Viewing & Photographing",
    place: "Saariselkä",
    duration: "4 h",
    sid: "visit_home_pick_auroras_northern_lights_viewing_photogra",
  },
  {
    path: "sirkka-l139331/levi-northern-lights-magic-and-stargazing-by-telescope-t600186",
    price: "109 €",
    title: "Northern Lights Tour and Stargazing by Telescope",
    place: "Levi",
    duration: "3 h",
    sid: "visit_home_pick_northern_lights_tour_and_stargazing_by_t",
  },
];

/** laplandnature */
export const NATURE_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-hiking-and-snowshoeing-adventure-in-lapland-t183797",
    price: "105 €",
    title: "Hiking and Snowshoeing Adventure in Lapland",
    place: "Rovaniemi",
    duration: "3 h",
    sid: "nature_home_pick_hiking_and_snowshoeing_adventure_in_lapl",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-frozen-waterfalls-of-korouoma-winter-adventure-t462678",
    price: "145 €",
    title: "Frozen Waterfalls of Korouoma Canyon & Pro Photos",
    place: "Rovaniemi",
    duration: "6,5 h",
    sid: "nature_home_pick_frozen_waterfalls_of_korouoma_canyon_pro",
  },
  {
    path: "sirkka-l139331/snowshoeing-in-the-national-park-t449218",
    price: "279 €",
    title: "Private Pallas-Yllästunturi National Park Snowshoeing",
    place: "Levi",
    duration: "5,5 h",
    sid: "nature_home_pick_private_pallas_yll_stunturi_national_par",
  },
  {
    path: "saariselka-l181615/saariselka-snowshoeing-tour-in-urho-kekkonen-national-park-t800450",
    price: "75 €",
    title: "Snowshoeing Tour in Urho Kekkonen National Park",
    place: "Saariselkä",
    duration: "2 - 4 h",
    sid: "nature_home_pick_snowshoeing_tour_in_urho_kekkonen_nation",
  },
];

/** laplandchristmas */
export const CHRISTMAS_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-arctic-snowhotel-tour-t302863",
    price: "37 €",
    title: "Arctic SnowHotel",
    place: "Rovaniemi",
    duration: "3,5 h",
    sid: "christmas_home_pick_arctic_snowhotel",
  },
  {
    // Vaihdettu 2026-07-31 (Vesa: "kaksi samantyylistä vierekkäin ei hyvä" —
    // rivi 2 oli toinen SnowHotel-variantti, jonka duration-kenttä oli lisäksi
    // roskaa "2 minutes - 4 hours"). t434430 EI ole katalogissa (löytyi GYG-hausta,
    // title-verifioitu selaimessa 2026-07-31). Hinta+kesto luettu tuotesivun
    // omasta HTML:stä suomalaisella IP:llä 2026-08-01 (startPrice €150,
    // "Kesto 3 tuntia") → per-rivi priceAsOf, jottei 29.7.-katalogipäiväys valehtele.
    path: "rovaniemi-l2653/the-santa-claus-village-visit-t434430",
    price: "150 €",
    priceAsOf: "2026-08-01",
    title: "The Santa Claus Village Visit",
    place: "Rovaniemi",
    duration: "3 h",
    sid: "christmas_home_pick_santa_claus_village",
  },
  {
    path: "sirkka-l139331/levi-winter-wilderness-husky-reindeer-safari-combo-tour-t986260",
    price: "149 €",
    title: "3-in-1 Combo Husky, Reindeer & Snowmobile sleigh ride",
    place: "Levi",
    duration: "2 h",
    sid: "christmas_home_pick_3_in_1_combo_husky_reindeer_snowmobile_s",
  },
  {
    path: "saariselka-l181615/saariselka-northern-lights-reindeer-sledding-tour-t805244",
    price: "189 €",
    title: "Northern Lights & Reindeer Sledding Tour",
    place: "Saariselkä",
    duration: "2,5 h",
    sid: "christmas_home_pick_northern_lights_reindeer_sledding_tour",
  },
];

/** laplandwellness-com */
export const WELLNESS_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/traditional-finnish-sauna-and-ice-swimming-in-rovaniemi-t540471",
    price: "80 €",
    title: "Traditional Sauna and Ice Swimming Experience",
    place: "Rovaniemi",
    duration: "1,5 h",
    sid: "wellness_home_pick_traditional_sauna_and_ice_swimming_exper",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-arctic-sauna-and-hot-tub-with-northern-lights-t192594",
    price: "159 €",
    title: "Northern Lights with Arctic Sauna, Jacuzzi & BBQ",
    place: "Rovaniemi",
    duration: "3 h",
    sid: "wellness_home_pick_northern_lights_with_arctic_sauna_jacuzz",
  },
  {
    path: "sirkka-l139331/authentic-finnish-wooden-sauna-with-dinner-in-the-wilderness-t675809",
    price: "359 €",
    title: "Private Traditional Sauna, Ice Dip and Dinner in the Wild",
    place: "Lappi",
    duration: "4 h",
    sid: "wellness_home_pick_private_traditional_sauna_ice_dip_and_di",
  },
  {
    path: "ruka-l192178/ruka-pyhapiilo-sauna-duo-smoke-ice-sauna-experience-t1167518",
    price: "90 €",
    title: "Pyhäpiilo sauna duo: smoke & ice sauna experience",
    place: "Ruka",
    duration: "2 h",
    sid: "wellness_home_pick_pyh_piilo_sauna_duo_smoke_ice_sauna_expe",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Teemalistat, ei sivustolistat. Lisätty 2026-08-02 laplandgifts.com:in
// lahjaelämyksiä varten, mutta vapaasti minkä tahansa sivuston käytettävissä.
//
// Nämä kaksi eivät kuulu millekään yksittäiselle sivustolle, koska ne poimittiin
// TEEMAN eivätkä kohdesivuston perusteella: ruokailut sekä taide ja kulttuuri
// olivat ainoat lahjakategoriat joista laplandgiftsillä ei ollut yhtään riviä.
//
// 🔴 Nämä EIVÄT kumoa alla olevaa "dining saa vain kategorialinkin" -päätöstä.
// Se koskee sitä, mitä `food-drinks-tc103`-listauksen kärki tarjoaa: se on
// edelleen valtaosin moottorikelkkasafari-lounaineen. Alla olevat kymmenen
// riviä löytyivät suodattamalla koko 839 tuotteen katalogia tuotteen SLUGIN
// perusteella, ei kategorian, ja sitten avaamalla jokainen selaimessa. Kaikki
// kymmenen palauttivat 200, eivät uudelleenohjanneet ja renderöivät varaus-
// painikkeen 2026-08-02. Kaksi otsikkoa erosi katalogin arvosta ja ne on
// kirjoitettu tähän GYG:n OMASSA muodossa:
//   - t823102 katalogissa "Lapland traditional pancake dinner with local
//     delights", livenä "Ylläs: Fireside tasting in a traditional lavvo"
//   - t1205565 katalogissa "Architecture by Alvar Aalto tour with transfers",
//     livenä "Rovaniemi: Alvar Aalto Architecture Tour with Pickup"
// Katalogin sanamuodon julkaiseminen olisi luvannut tuotenimen jota
// järjestäjä ei käytä.
//
// Hinnat luettiin 2026-08-02, ei katalogin ajopäivänä 2026-07-29, joten jokaisella
// rivillä on oma `priceAsOf`. Muuten 29.7.-päiväys valehtelisi näistä riveistä.
// ─────────────────────────────────────────────────────────────────────────────

/** Ruokailuelämykset: ruoka on tuote, ei safarin sivujuonne. */
export const DINING_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-insider-guided-food-tour-with-5-tastings-t1101825",
    price: "129 €",
    priceAsOf: "2026-08-02",
    title: "Insider Guided Food Tour with 5 Tastings",
    place: "Rovaniemi",
    duration: "3,5 h",
    sid: "dining_gift_food_tour_rovaniemi",
  },
  {
    path: "saariselka-l181615/saariselka-wilderness-dinner-chef-s-special-evening-t834694",
    price: "119 €",
    priceAsOf: "2026-08-02",
    title: "Wilderness Dinner - Chef's Special Evening",
    place: "Saariselkä",
    duration: "3 h",
    sid: "dining_gift_wilderness_dinner_saariselka",
  },
  {
    // 🔴 Slug lupaa lettuja, live-otsikko puhuu lavvusta. Otsikko on livestä.
    path: "kittila-l165074/lapland-traditional-pancake-dinner-with-local-delights-t823102",
    price: "75 €",
    priceAsOf: "2026-08-02",
    title: "Fireside tasting in a traditional lavvo",
    place: "Ylläs",
    duration: "1,5 h",
    sid: "dining_gift_lavvo_tasting_yllas",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-private-glass-igloo-dinner-under-northern-lights-t672688",
    price: "399 €",
    priceAsOf: "2026-08-02",
    title: "Private Glass Igloo Dinner Under Northern Lights",
    place: "Rovaniemi",
    duration: "3 h",
    sid: "dining_gift_glass_igloo_dinner_rovaniemi",
  },
  {
    path: "ruka-l192178/ruka-3-course-kuusamo-wild-food-dinner-t1205230",
    price: "78 €",
    priceAsOf: "2026-08-02",
    title: "3-Course Kuusamo Wild Food Dinner",
    place: "Ruka",
    duration: "2,5 h",
    sid: "dining_gift_wild_food_dinner_ruka",
  },
];

/**
 * Taide ja kulttuuri: museot, arkkitehtuuri ja kullanhuuhdonta.
 *
 * Arktikum ja Korundi ovat pääsylippuja, joten niillä ei ole kestoa: sisään
 * pääsee milloin tahansa aukioloaikana. Puuttuva kesto on parempi kuin keksitty.
 */
export const CULTURE_PICKS: GygPick[] = [
  {
    path: "rovaniemi-l2653/rovaniemi-arktikum-science-centre-and-museum-entry-ticket-t833435",
    price: "22 €",
    priceAsOf: "2026-08-02",
    title: "Arktikum Science Centre and Museum Entry Ticket",
    place: "Rovaniemi",
    sid: "culture_gift_arktikum_rovaniemi",
  },
  {
    path: "rovaniemi-l2653/rovaniemi-korundi-art-museum-entry-ticket-t833481",
    price: "13 €",
    priceAsOf: "2026-08-02",
    title: "Korundi Art Museum Entry Ticket",
    place: "Rovaniemi",
    sid: "culture_gift_korundi_rovaniemi",
  },
  {
    path: "inari-l245909/inari-cultural-day-lake-inari-cruise-siida-sami-museum-t1005215",
    price: "143 €",
    priceAsOf: "2026-08-02",
    title: "Inari Cultural Day - Lake Inari Cruise & Siida Sami Museum",
    place: "Inari",
    duration: "6 h",
    sid: "culture_gift_siida_inari",
  },
  {
    // 🔴 Slug sanoo "with transfers", live-otsikko "with Pickup". Otsikko on livestä.
    path: "rovaniemi-l2653/rovaniemi-architecture-by-alvar-aalto-tour-with-transfers-t1205565",
    price: "89 €",
    priceAsOf: "2026-08-02",
    title: "Alvar Aalto Architecture Tour with Pickup",
    place: "Rovaniemi",
    duration: "2,5 h",
    sid: "culture_gift_alvar_aalto_rovaniemi",
  },
  {
    path: "ivalo-l187030/ivalo-saariselka-gold-panning-in-lapland-s-gold-rush-area-t1243827",
    price: "129 €",
    priceAsOf: "2026-08-02",
    title: "Gold Panning in Lapland's Gold Rush Area",
    place: "Ivalo and Saariselkä",
    duration: "4 h",
    sid: "culture_gift_gold_panning_kuttura",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Category links, not product cards.
//
// These four sites do NOT get a "book this exact thing" showcase, because the
// GetYourGuide supply does not honestly match what the site promises. Measured
// 2026-07-30 against the 839-product catalogue:
//
//   skiresorts  ski-snowboard has 56 results, but the top-ranked ones are ice
//               karting and husky sledding. A ski-resort page headlining a husky
//               ride is a mismatch the visitor notices.
//   dining      food-drinks has 312 results, yet they are overwhelmingly
//               snowmobile-safari-with-lunch and aurora-tour-with-BBQ. Food is
//               the side dish, not the product.
//   food        same pool, same problem.
//   transport   transfers + airport-transfers total 54 across 5 destinations,
//               and several are sightseeing tours wearing the word "transfer".
//
// 🔴 nightlife-bars-tc109 has TWO results in the entire region, so laplandbars
// and laplandnightlife get nothing here at all. Forcing four cards would mean
// inventing relevance, which is the same defect as a fabricated statistic.
//
// A category link stays honest and never goes stale: GetYourGuide maintains the
// list, so it cannot rot the way a hardcoded product id does.
// ─────────────────────────────────────────────────────────────────────────────

export interface GygCategoryLink {
  /** `<location-lNNN>/<name-tcNNN>` — verified live. */
  path: string;
  /** Live result count when verified. Documentation only, never rendered. */
  results: number;
  sid: string;
}

const LAPLAND = "lapland-finland-l2652";

export const CATEGORY_LINKS: Record<string, GygCategoryLink[]> = {
  "laplandskiresorts-new": [
    { path: `${LAPLAND}/ski-snowboard-tc146`, results: 56, sid: "skiresorts_cat_ski_snowboard" },
    { path: `${LAPLAND}/snow-winter-sports-tc113`, results: 648, sid: "skiresorts_cat_winter_sports" },
  ],
  "laplanddining-new": [
    { path: `${LAPLAND}/food-drinks-tc103`, results: 312, sid: "dining_cat_food_drinks" },
    { path: `${LAPLAND}/dinner-packages-tc100`, results: 44, sid: "dining_cat_dinner_packages" },
  ],
  "laplandfood-new": [
    { path: `${LAPLAND}/food-drinks-tc103`, results: 312, sid: "food_cat_food_drinks" },
    { path: `${LAPLAND}/dinner-packages-tc100`, results: 44, sid: "food_cat_dinner_packages" },
  ],
  "laplandtransport-aee5fcf1": [
    { path: `${LAPLAND}/airport-transfers-tc153`, results: 17, sid: "transport_cat_airport" },
    { path: `${LAPLAND}/transfers-tc152`, results: 37, sid: "transport_cat_transfers" },
  ],
};

/** Affiliate href for a category link, through the Worker. */
export function gygCategoryHref(link: GygCategoryLink, lang?: string): string {
  return gygHref({ path: link.path, title: "", place: "", sid: link.sid }, lang);
}

/** Ylellisyys-sivun suuret päivät (laplandgifts /luxury + /experiences 'icebreaker'). */
export const LUXURY_PICKS: GygPick[] = [
  {
    // Vesa 5.9.2026 (Ylellisyys-sivu): "eihän täällä ole edes sitä Kemin
    // kelluntaa meressä Sampo-murtajan kanssa?" Hinta luettu GYG:n fi-sivulta
    // 2026-09-05 (alkaen 402 €), kesto listauksesta (6,5–7 h). Tuotesivu
    // verifioitu selaimessa (curl 403 partner-parametreilla).
    path: "kemi-l98127/kemi-iltapaivan-jaanmurtaja-sampo-risteily-ja-jaalla-kellunta-t504004",
    price: "402 €",
    title: "Icebreaker Sampo Cruise with Ice Floating",
    place: "Kemi",
    duration: "6.5–7 h",
    sid: "gifts_luxury_pick_icebreaker_kemi",
  },
];
