import { MapPin, Clock, Ticket, ArrowUpRight } from 'lucide-react';
import { TOURS_PICKS, gygHref, GYG_PRICE_AS_OF } from '../shared/gyg/picks';
import { GYG_IMAGES } from '../data/gygImages';
import { useLang } from '../i18n/useLang';

/**
 * Direct GetYourGuide product deep links — generated by
 * scripts/gyg-rollout.mjs on 2026-07-30. Edit the generator, not this file.
 *
 * The WHOLE card is the link. Every path in shared/gyg/picks.ts was opened in
 * a real browser before shipping; a wrong or delisted GetYourGuide id does not
 * 404, it redirects to a city listing with HTTP 200.
 *
 * Price IS rendered, but never as ours: it is GetYourGuide's own
 * "from" price on GYG_PRICE_AS_OF, printed with the source and that date beside
 * it. Euros — an earlier note in this codebase claimed USD, which was wrong and
 * came from a JSON-LD field the crawler never stored. No "per person" label:
 * the catalogue does not record the unit and some products are priced per group.
 *
 * Ratings and review counts stay out. We cannot keep them current, and a stale
 * "4.6 (869)" is a claim about other people's experience, not a fact.
 */

const COPY = {
  "kicker": {
    "en": "Book now",
    "fi": "Varaa heti",
    "de": "Jetzt buchen",
    "ja": "今すぐ予約",
    "es": "Reserva ya",
    "pt-BR": "Reserve agora",
    "zh-CN": "立即预订",
    "ko": "지금 예약",
    "fr": "Réservez",
    "it": "Prenota ora",
    "nl": "Boek nu",
    "sv": "Boka nu"
  },
  "ctaProduct": {
    "en": "Check availability",
    "fi": "Katso saatavuus",
    "de": "Verfügbarkeit prüfen",
    "ja": "空き状況を見る",
    "es": "Ver disponibilidad",
    "pt-BR": "Ver disponibilidade",
    "zh-CN": "查看可订日期",
    "ko": "예약 가능 여부 확인",
    "fr": "Voir les disponibilités",
    "it": "Vedi disponibilità",
    "nl": "Bekijk beschikbaarheid",
    "sv": "Se tillgänglighet"
  },
  "ctaCategory": {
    "en": "Browse all",
    "fi": "Selaa kaikki",
    "de": "Alle ansehen",
    "ja": "すべて見る",
    "es": "Ver todo",
    "pt-BR": "Ver tudo",
    "zh-CN": "查看全部",
    "ko": "전체 보기",
    "fr": "Voir tout",
    "it": "Vedi tutto",
    "nl": "Bekijk alles",
    "sv": "Se alla"
  },
  "via": {
    "en": "via GetYourGuide",
    "fi": "GetYourGuiden kautta",
    "de": "über GetYourGuide",
    "ja": "GetYourGuide 経由",
    "es": "con GetYourGuide",
    "pt-BR": "via GetYourGuide",
    "zh-CN": "通过 GetYourGuide",
    "ko": "GetYourGuide 제공",
    "fr": "via GetYourGuide",
    "it": "tramite GetYourGuide",
    "nl": "via GetYourGuide",
    "sv": "via GetYourGuide"
  },
  "priceFrom": {
    "en": "from",
    "fi": "alkaen",
    "de": "ab",
    "ja": "〜より",
    "es": "desde",
    "pt-BR": "a partir de",
    "zh-CN": "起价",
    "ko": "부터",
    "fr": "à partir de",
    "it": "da",
    "nl": "vanaf",
    "sv": "från"
  },
  "priceSource": {
    "en": "Price on GetYourGuide",
    "fi": "Hinta GetYourGuidessa",
    "de": "Preis auf GetYourGuide",
    "ja": "GetYourGuide の価格",
    "es": "Precio en GetYourGuide",
    "pt-BR": "Preço no GetYourGuide",
    "zh-CN": "GetYourGuide 价格",
    "ko": "GetYourGuide 가격",
    "fr": "Prix sur GetYourGuide",
    "it": "Prezzo su GetYourGuide",
    "nl": "Prijs op GetYourGuide",
    "sv": "Pris på GetYourGuide"
  },
  "headingProduct": {
    "en": "Bookable today",
    "fi": "Varattavissa tänään",
    "de": "Heute buchbar",
    "ja": "今日予約できる体験",
    "es": "Reservable hoy",
    "pt-BR": "Reservável hoje",
    "zh-CN": "今天即可预订",
    "ko": "오늘 예약 가능",
    "fr": "Réservable aujourd’hui",
    "it": "Prenotabile oggi",
    "nl": "Vandaag te boeken",
    "sv": "Bokningsbart i dag"
  },
  "ledeProduct": {
    "en": "Hand-picked guided tours, bookable online through GetYourGuide.",
    "fi": "Poimitut opastetut retket, varattavissa verkossa GetYourGuiden kautta.",
    "de": "Ausgewählte geführte Touren — online über GetYourGuide buchbar.",
    "ja": "厳選したガイド付きツアー。GetYourGuide でオンライン予約できます。",
    "es": "Tours guiados seleccionados, reservables en línea con GetYourGuide.",
    "pt-BR": "Passeios guiados selecionados, reserváveis online via GetYourGuide.",
    "zh-CN": "精选向导带队行程，可通过 GetYourGuide 在线预订。",
    "ko": "엄선한 가이드 투어 — GetYourGuide에서 온라인 예약.",
    "fr": "Une sélection de visites guidées, réservables en ligne via GetYourGuide.",
    "it": "Tour guidati selezionati, prenotabili online tramite GetYourGuide.",
    "nl": "Geselecteerde begeleide tochten, online te boeken via GetYourGuide.",
    "sv": "Utvalda guidade turer — bokas online via GetYourGuide."
  },
  "headingCategory": {
    "en": "Browse and book on GetYourGuide",
    "fi": "Selaa ja varaa GetYourGuidessa",
    "de": "Auf GetYourGuide stöbern und buchen",
    "ja": "GetYourGuide で探して予約",
    "es": "Explora y reserva en GetYourGuide",
    "pt-BR": "Explore e reserve no GetYourGuide",
    "zh-CN": "在 GetYourGuide 浏览并预订",
    "ko": "GetYourGuide에서 둘러보고 예약",
    "fr": "Parcourez et réservez sur GetYourGuide",
    "it": "Sfoglia e prenota su GetYourGuide",
    "nl": "Bekijk en boek op GetYourGuide",
    "sv": "Bläddra och boka på GetYourGuide"
  },
  "ledeCategory": {
    "en": "A partner-maintained list, always current — we do not name a single tour here.",
    "fi": "Kumppanin ylläpitämä lista, aina ajantasainen; emme nimeä yksittäistä retkeä.",
    "de": "Eine vom Partner gepflegte Liste, immer aktuell.",
    "ja": "パートナーが管理する最新のリストです。",
    "es": "Una lista mantenida por el socio, siempre actualizada.",
    "pt-BR": "Uma lista mantida pelo parceiro, sempre atual.",
    "zh-CN": "由合作伙伴维护的列表，始终保持最新。",
    "ko": "파트너가 관리하는 항상 최신 목록입니다.",
    "fr": "Une liste tenue à jour par le partenaire.",
    "it": "Un elenco aggiornato dal partner.",
    "nl": "Een door de partner bijgehouden, actuele lijst.",
    "sv": "En lista som partnern håller uppdaterad."
  }
};

/**
 * The as-of date next to each price, in the page's locale. Not "today" —
 * the day the price was actually read off GetYourGuide, which is the only date
 * we can stand behind.
 */
const fiDate = (iso: string, locale: string): string => {
  const d = new Date(iso + 'T00:00:00Z');
  // timeZone UTC because the stamp is a plain date: without it a reader west of
  // UTC is shown the previous day. Locale is the page's, never the browser's.
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString(locale, { day: 'numeric', month: 'numeric', year: 'numeric', timeZone: 'UTC' });
};

export default function GygPicks() {
  const lang = useLang();
  const t = (m: Record<string, string>): string => m[lang] ?? m.en;
  const L = COPY;
  const rows = TOURS_PICKS;

  if (!rows.length) return null;

  return (
    <section className="py-16 sm:py-20 px-4 sm:px-6 bg-[#0F172A]">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10 sm:mb-12">
          <p className="font-bold tracking-[0.18em] uppercase text-sm mb-3 text-[#22D3EE]">{t(L.kicker)}</p>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 text-[#F9FAFB]">
            {t(L.headingProduct)}
          </h2>
          <p className="max-w-2xl text-white/70">{t(L.ledeProduct)}</p>
        </div>

        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        {rows.map((p) => (
          <a
            key={p.path}
            href={gygHref(p, lang)}
            target="_blank"
            rel="sponsored nofollow noopener"
            className="group flex flex-col overflow-hidden rounded-2xl border bg-white/5 border-white/10 no-underline transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:border-[#22D3EE]/50"
          >
            {GYG_IMAGES[p.path] ? (
              <img
                src={GYG_IMAGES[p.path]}
                alt=""
                loading="lazy"
                className="aspect-[4/3] w-full object-cover transition-transform duration-500 group-hover:scale-105"
              />
            ) : (
              /* Brand-approved fallback: a gradient, never a stock photo. */
              <div className="aspect-[4/3] w-full bg-gradient-to-br from-[#0d2818] via-[#0F172A] to-[#1e1b4b]" />
            )}

            <div className="flex flex-1 flex-col p-5">
              <p className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#22D3EE]">
                <MapPin className="h-3.5 w-3.5" aria-hidden="true" />
                {p.place}
              </p>

              <h3 className="mt-2 flex-1 text-base font-bold leading-snug text-[#F9FAFB]">{p.title}</h3>

              {/* Only when a real length exists — one source row carried a sales
                  badge in this field, and a badge is not a duration. */}
              {p.duration && (
                <p className="mt-2 inline-flex items-center gap-1.5 text-sm text-white/60">
                  <Clock className="h-3.5 w-3.5" aria-hidden="true" />
                  {p.duration}
                </p>
              )}

              {/* GetYourGuide's OWN "from" price, with source and date beside it.
                  It is not our price and we cannot keep it current — the partner
                  changes it. Rendering it bare would be a promise we break on
                  their behalf; rendering it dated is a fact about a moment.
                  Deliberately no "per person": spot checks showed per-person on
                  the rows we opened, but the catalogue does not record the unit
                  and some GetYourGuide products are priced per group. */}
              {p.price && (
                <p className="mt-3 flex items-baseline gap-1.5">
                  <span className="text-[11px] uppercase tracking-wider text-white/60">{t(L.priceFrom)}</span>
                  <span className="text-lg font-bold text-[#F9FAFB]">{p.price}</span>
                </p>
              )}

              <span className="mt-4 inline-flex items-center justify-center gap-2 rounded-full bg-[#DB2777] px-4 py-2.5 text-sm font-bold text-white transition-opacity group-hover:opacity-90">
                <Ticket className="h-4 w-4" aria-hidden="true" />
                {t(L.ctaProduct)}
                <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
              </span>

              <span className="mt-2 text-center text-[11px] text-white/60">
                {p.price ? `${t(L.priceSource)} ${fiDate(GYG_PRICE_AS_OF, lang)}` : t(L.via)}
              </span>
            </div>
          </a>
        ))}
        </div>
      </div>
    </section>
  );
}
