/**
 * scripts/sync-shared.mjs — refresh this repo's VENDORED copy of the monorepo's shared/ library.
 *
 * 🔴 CANONICAL FILE, IDENTICAL IN EVERY SITE. The source of truth is lv-ops `scripts/templates/sync-shared.mjs`;
 * gate:sync-shared fails when a site's copy differs from it. Do not edit this file in a site repo: edit the
 * template, run `node --test scripts/lib/sync_shared_template.test.mjs`, then roll it out from lv-ops with
 * `node scripts/rollout_sync_shared.mjs --write`. What differs per site lives in scripts/sync-shared.json.
 *
 * ─── Why vendoring ────────────────────────────────────────────────────────────────────────────────
 * src/ imports shared components (Footer, CookieBanner, NewsletterPopup, Legal/*, …) that live in the private
 * parent monorepo (Laplandvibes/lv-ops) at ../shared, a directory that does not exist in this GitHub repo. A
 * committed copy under src/shared/ (plus the monorepo root files named in scripts/sync-shared.json, e.g. the
 * prerenderer) is what lets GitHub Actions build the site from a plain checkout. In CI ../shared is absent, this
 * script exits 0 and the committed snapshot is used as-is.
 *
 * ─── What a local run does (automatically before every `npm run dev` / `npm run build`) ────────────
 *   • REFRESH-ONLY. Only files this repo already vendors are updated. New shared files are never pulled in and
 *     nothing is deleted. Vendor a new one by hand: git -C .. show origin/main:shared/<file> > src/shared/<file>
 *   • COMMITTED CONTENT ONLY. Versions come from git objects, never from the monorepo working tree, which other
 *     sessions routinely hold half-edited (26.7.2026: a working-tree copy shipped another session's edit).
 *   • NEWEST COMMITTED VERSION WINS among three monorepo refs: HEAD, HEAD's upstream and origin/main.
 *   • 🔴 FORWARD ONLY. A vendored file is overwritten only when its current content appears EARLIER in that
 *     version's own history, i.e. the write moves it forward. Newer, on another branch, patched in place: HELD.
 *   • When the refs have DIVERGED on a file (26.9.: carhelp vs main on Footer, AdUnit, NewsletterPopup, …), the copy
 *     moves forward along a line it is behind, origin/main first; a copy already at one line's tip is left alone and
 *     listed in a Note, since only merging the branches upstream can reconcile them.
 *
 * ─── Why forward only (measured 26.9.2026) ────────────────────────────────────────────────────────
 * The monorepo's main checkout sits on a long-lived branch (claude/carhelp-lapland-20260909) that was 22 commits
 * behind its own upstream and had diverged from origin/main by 745/144 commits. Canonical shared/ changes are made
 * in worktrees, merged to origin/main and copied straight into the site repos, and rollouts such as
 * rollout_kielietuliite.mjs patch the vendored copies in place. The previous scripts copied
 * `git show HEAD:shared/<file>` over anything that differed, and their two guards looked only at uncommitted
 * state, so a local build would have reverted the 25.9. locale-prefixed footer links on six sites, the 26.9.
 * legal-text fixes on three and an AdUnit fix on one. The hub's variant mirrored the monorepo WORKING TREE
 * wholesale (rm + cp), pulling in anyone's uncommitted edit.
 *
 * ─── Guards (a file is written only when all three pass) ──────────────────────────────────────────
 *   (a) not uncommitted in THIS repo: a refresh is delete-and-replace, the one edit another session cannot get
 *       back (lv_permanent_rules §4);
 *   (c) the vendored content is behind the newest committed version (above). `--force <path>` adopts the
 *       canonical for a held file on purpose, e.g. once a patched copy's change has landed upstream;
 *   (b) not uncommitted in the MONOREPO: someone is editing it there right now; wait until it is committed.
 *
 * ─── Usage ─────────────────────────────────────────────────────────────────────────────────────────
 *   node scripts/sync-shared.mjs                   refresh (predev/prebuild; also `npm run sync:shared`)
 *   node scripts/sync-shared.mjs --dry             report only, write nothing
 *   node scripts/sync-shared.mjs --force <path>…   also overwrite these files when HELD by guard (c)
 *
 * scripts/sync-shared.json:  { "rootFiles": ["_prerender_routes.mjs"], "followImports": true }
 *   rootFiles      monorepo ROOT files vendored into scripts/ (not shared/); [] when the site forked its own.
 *   followImports  also vendor the ./x.mjs modules those files import. The prerenderer was split into helpers in
 *                  2026-08, and copying only the entry point broke builds with ERR_MODULE_NOT_FOUND.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const TAG = '[sync-shared]';
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const monorepoRoot = resolve(repoRoot, '..');
const vendoredShared = join(repoRoot, 'src', 'shared');
const MARKER = '_VENDORED-DO-NOT-EDIT.md';
const posix = (p) => p.replace(/\\/g, '/');

if (!existsSync(join(monorepoRoot, 'shared'))) {
  console.log(`${TAG} ../shared not found (CI / standalone checkout) — using committed vendored copy.`);
  if (!existsSync(vendoredShared)) {
    console.error(`${TAG} FATAL: src/shared/ is missing too. The vendored copy was never committed.`);
    console.error(`${TAG} Run \`node scripts/sync-shared.mjs\` inside the local monorepo and commit src/shared/.`);
    process.exit(1);
  }
  process.exit(0);
}

const fail = (msg) => { console.error(`${TAG} FATAL: ${msg}`); process.exit(1); };
// A name, not a join(…, 'scripts', 'x.json') literal: lv-ops gate:tyokalut reads such literals as ITS own dependencies.
const CONFIG_FILE = 'sync-shared.json';

// ─── arguments + per-site configuration ─────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const DRY = argv.includes('--dry');
const FORCE = new Set();
for (let i = 0; i < argv.length; i++) {
  if (argv[i] !== '--force') continue;
  while (i + 1 < argv.length && !argv[i + 1].startsWith('--')) FORCE.add(posix(argv[++i]).replace(/^\.\//, ''));
}

function readConfig() {
  const p = join(repoRoot, 'scripts', CONFIG_FILE);
  if (!existsSync(p)) {
    console.warn(`${TAG} WARNING: scripts/sync-shared.json is missing — syncing src/shared/ only, no root files.`);
    return { rootFiles: [], followImports: false };
  }
  let c;
  try { c = JSON.parse(readFileSync(p, 'utf8')); } catch (e) { fail(`scripts/sync-shared.json is not valid JSON (${e.message}).`); }
  const fileName = (f) => typeof f === 'string' && /^[\w.-]+\.mjs$/.test(f);
  if (!c || !Array.isArray(c.rootFiles) || !c.rootFiles.every(fileName) || typeof c.followImports !== 'boolean') {
    fail('scripts/sync-shared.json must be {"rootFiles": ["<monorepo root file>.mjs", …], "followImports": true|false}.');
  }
  return c;
}
const config = readConfig();

// ─── git plumbing (monorepo) ─────────────────────────────────────────────────────────────────────────
function git(args, input) {
  const r = spawnSync('git', ['-C', monorepoRoot, '-c', 'core.quotePath=false', ...args], { input, maxBuffer: 1024 * 1024 * 1024 });
  if (r.error) throw r.error;
  return { ok: r.status === 0, buf: r.stdout, out: r.stdout ? r.stdout.toString('utf8') : '' };
}

/** Git blob id of the content with CRLF → LF: vendored copies check out CRLF on Windows, the monorepo is LF. */
function normId(buf) {
  const s = buf.toString('latin1');
  const b = s.includes('\r\n') ? Buffer.from(s.replace(/\r\n/g, '\n'), 'latin1') : buf;
  return createHash('sha1').update(`blob ${b.length}\0`).update(b).digest('hex');
}

const blobs = new Map(); // raw blob id → Buffer
const norms = new Map(); // raw blob id → normalised id
function readBlobs(ids) {
  const want = [...new Set(ids)].filter((id) => id && !blobs.has(id));
  if (!want.length) return;
  const r = git(['cat-file', '--batch'], `${want.join('\n')}\n`);
  if (!r.ok || !r.buf) throw new Error('git cat-file --batch failed');
  const b = r.buf;
  let i = 0;
  while (i < b.length) {
    const nl = b.indexOf(10, i);
    if (nl < 0) break;
    const [id, type, size] = b.subarray(i, nl).toString('latin1').split(' ');
    if (type === 'missing' || size === undefined) { i = nl + 1; continue; }
    const n = Number(size);
    blobs.set(id, b.subarray(nl + 1, nl + 1 + n));
    i = nl + 1 + n + 1;
  }
}
function norm(id) {
  if (!norms.has(id)) norms.set(id, blobs.has(id) ? normId(blobs.get(id)) : null);
  return norms.get(id);
}

/** HEAD, its upstream and origin/main — deduplicated by commit. rank: preference when they have diverged. */
function resolveRefs() {
  const refs = [];
  const add = (label, sha, rank) => {
    const same = refs.find((x) => x.sha === sha);
    if (!same) refs.push({ sha, labels: [label], rank });
    else { if (!same.labels.includes(label)) same.labels.push(label); same.rank = Math.min(same.rank, rank); }
  };
  // Two spawns in the normal case (each costs 0.1–0.7 s on a busy Windows machine); one per ref as the fallback.
  const names = git(['rev-parse', '--abbrev-ref', 'HEAD', '@{upstream}']);
  const shas = names.ok ? git(['rev-parse', 'HEAD', '@{upstream}', 'refs/remotes/origin/main']) : { ok: false };
  if (names.ok && shas.ok) {
    const [branch, upstream] = names.out.trim().split(/\r?\n/);
    const [head, up, main] = shas.out.trim().split(/\r?\n/);
    add(branch === 'HEAD' ? 'HEAD (detached)' : `HEAD (${branch})`, head, 2);
    add(upstream, up, 1);
    add('origin/main', main, 0);
  } else {
    const one = (rev) => { const r = git(['rev-parse', '--verify', '--quiet', `${rev}^{commit}`]); return r.ok ? r.out.trim() : null; };
    const branch = git(['symbolic-ref', '--short', '-q', 'HEAD']);
    const head = one('HEAD');
    if (head) add(branch.ok ? `HEAD (${branch.out.trim()})` : 'HEAD (detached)', head, 2);
    const up = git(['rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{upstream}']);
    const upSha = up.ok && up.out.trim() ? one(up.out.trim()) : null;
    if (upSha) add(up.out.trim(), upSha, 1);
    const main = one('refs/remotes/origin/main');
    if (main) add('origin/main', main, 0);
  }
  for (const ref of refs) ref.name = ref.labels.find((l) => !l.startsWith('HEAD')) ?? ref.labels[0];
  return refs;
}

/** path → blob id for shared/** and the root-level *.mjs modules, at one ref. */
function treeOf(ref) {
  const m = new Map();
  for (const entry of git(['ls-tree', '-r', '--full-tree', '-z', ref.sha]).out.split('\0')) {
    const tab = entry.indexOf('\t');
    if (tab < 0) continue;
    const [, type, id] = entry.slice(0, tab).split(' ');
    const path = entry.slice(tab + 1);
    if (type === 'blob' && (path.startsWith('shared/') || /^[\w.-]+\.mjs$/.test(path))) m.set(path, id);
  }
  return m;
}

/**
 * Parse `git log --format=%x01%H%x09%ct%x09%s --raw` into path → [{ c, t, s, old, id }], newest first. `old` is the
 * version at the commit's parent: it is how a merge result shows up (the next commit on top of it starts from it),
 * so the logs can skip -m, whose per-parent diffs of the big "Merge origin/main" commits were the slow part.
 */
function parseLog(out, wanted) {
  const res = new Map();
  const blob = (id) => (id && !/^0+$/.test(id) ? id : null);
  let cur = null;
  for (const line of out.split('\n')) {
    if (line.startsWith('\x01')) { const [c, t, ...s] = line.slice(1).split('\t'); cur = { c, t: Number(t), s: s.join('\t') }; continue; }
    if (!cur || !line.startsWith(':')) continue;
    const tab = line.indexOf('\t');
    const meta = line.slice(1, tab).split(' ');
    const path = line.slice(tab + 1);
    if (!wanted.has(path)) continue;
    if (!res.has(path)) res.set(path, []);
    res.get(path).push({ ...cur, old: blob(meta[2]), id: blob(meta[3]) });
  }
  return res;
}
function logPaths(revArgs, paths) {
  const wanted = new Set(paths);
  const merged = new Map();
  for (let i = 0; i < paths.length; i += 100) {
    const r = git(['log', ...revArgs, '--format=%x01%H%x09%ct%x09%s', '--raw', '--no-abbrev', '--no-renames', '--', ...paths.slice(i, i + 100)]);
    for (const [p, list] of parseLog(r.out, wanted)) merged.set(p, [...(merged.get(p) || []), ...list]);
  }
  return merged;
}

function dirtyIn(cwd, pathspecs) {
  const r = spawnSync('git', ['-C', cwd, 'status', '--porcelain', '-z', '--untracked-files=all', '--', ...pathspecs], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  const set = new Set();
  if (r.status !== 0) return set;
  const parts = r.stdout.split('\0');
  for (let i = 0; i < parts.length; i++) {
    if (parts[i].length < 4) continue;
    set.add(parts[i].slice(3));
    if (/^[RC]/.test(parts[i])) set.add(parts[++i]);
  }
  return set;
}

const date = (t) => new Date(t * 1000).toISOString().slice(0, 10);
const short = (c) => c.slice(0, 7);

// ─── the run ───────────────────────────────────────────────────────────────────────────────────────
let refs;
try { refs = resolveRefs(); } catch (e) { refs = []; }
if (!refs.length) {
  console.warn(`${TAG} WARNING: could not read the monorepo's git state (git missing?) — nothing synced, vendored copy used as-is.`);
  process.exit(0);
}
const trees = refs.map(treeOf);
readBlobs(trees.flatMap((t) => [...t.values()]));

function vendoredFiles(dir = vendoredShared) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    if (e.isDirectory()) return vendoredFiles(p);
    return e.name === MARKER && dir === vendoredShared ? [] : [posix(relative(vendoredShared, p))];
  });
}

/** Distinct committed versions of a monorepo path across the refs: [{ tip, refs: [index…] }]. */
function groupsOf(mono) {
  const groups = [];
  refs.forEach((ref, i) => {
    const id = trees[i].get(mono);
    if (!id) return;
    const tip = norm(id);
    const g = groups.find((x) => x.tip === tip);
    if (g) g.refs.push(i); else groups.push({ tip, raw: id, refs: [i] });
  });
  return groups;
}

const siteDirty = dirtyIn(repoRoot, ['src/shared', 'scripts']);
// ':(glob)*.mjs' = monorepo root-level modules only, which covers the imports followImports discovers later.
const monoDirty = dirtyIn(monorepoRoot, ['shared', ':(glob)*.mjs']);
// ─── history: ONE commit graph + ONE path log over every branch, remote and tag ─────────────────────────
// Which versions a source ref has seen = the log entries whose commit that ref reaches, computed here from the
// graph instead of one `git log` per ref and file (36 spawns and 36 s for gifts on 26.9. → 2 spawns). The same
// data labels a HELD file: which commit, on which line, carries the vendored content.
let graph = null; // commit → parent commits
let entries = new Map(); // path → [{ c, t, s, old, id }]
function loadHistory(paths) {
  if (!paths.length) return;
  const revs = ['--branches', '--remotes', '--tags', ...refs.map((r) => r.sha)];
  graph = new Map();
  for (const line of git(['rev-list', '--parents', ...revs]).out.split('\n')) {
    const [c, ...parents] = line.trim().split(' ');
    if (c) graph.set(c, parents);
  }
  entries = logPaths([...revs, '--full-history'], [...new Set(paths)]);
  readBlobs([...entries.values()].flat().flatMap((e) => [e.old, e.id]));
}
const reachMemo = new Map();
function reaches(from) {
  if (!reachMemo.has(from)) {
    const seen = new Set();
    const stack = [from];
    while (stack.length) {
      const c = stack.pop();
      if (seen.has(c)) continue;
      seen.add(c);
      for (const p of graph?.get(c) || []) stack.push(p);
    }
    reachMemo.set(from, seen);
  }
  return reachMemo.get(from);
}
const versionsMemo = new Map();
/** Normalised ids of every version of path p that ref ri has seen (its tip included). */
function versionsIn(ri, p) {
  const key = `${ri}\t${p}`;
  if (!versionsMemo.has(key)) {
    const seen = reaches(refs[ri].sha);
    const s = new Set();
    for (const e of entries.get(p) || []) if (seen.has(e.c)) { if (e.old) s.add(norm(e.old)); if (e.id) s.add(norm(e.id)); }
    if (trees[ri].has(p)) s.add(norm(trees[ri].get(p)));
    versionsMemo.set(key, s);
  }
  return versionsMemo.get(key);
}
/** The newest commit in ref ri that set path p to `tip` — for display and for the NEWER test. */
const versionCommit = (ri, p, tip) => (entries.get(p) || []).find((e) => e.id && norm(e.id) === tip && reaches(refs[ri].sha).has(e.c)) || null;

/**
 * Decide one file. v = normalised id of the vendored content (null when not vendored yet).
 * kinds: current · stale · write (behind → forward) · add (missing root import) · ahead (guard c).
 */
function decide(item) {
  const groups = groupsOf(item.mono);
  if (!groups.length) return { kind: item.v === null ? 'absent' : 'stale' };
  if (item.v !== null && groups.length === 1 && groups[0].tip === item.v) return { kind: 'current' };
  const has = (g, id) => g.refs.some((ri) => versionsIn(ri, item.mono).has(id));
  const contains = (g, o) => g === o || has(g, o.tip);
  const rank = (g) => Math.min(...g.refs.map((ri) => refs[ri].rank));
  // Lines = versions no other version has passed, preferred first (origin/main, upstream, HEAD). One line = the
  // newest version; several = the refs diverged on this file (26.9.: carhelp and main on Footer, AdUnit, …).
  const lines = groups.filter((g) => !groups.some((o) => o !== g && contains(o, g) && !contains(g, o))).sort((a, b) => rank(a) - rank(b));
  // Behind a line = seen by a ref whose own tip that line has already passed. Transitive on purpose: the same change
  // often reaches another branch as a cherry-pick with a different commit, so exact ancestry alone would hold copies
  // that are plainly older.
  const behind = (line) => groups.some((g) => contains(line, g) && g.refs.some((ri) => versionsIn(ri, item.mono).has(item.v)));
  // Already the tip of a line: nothing to move. Otherwise forward along the first line it is behind — main when it is
  // behind both, its own line when that is the only forward move. Behind none: HELD.
  const target = lines.find((l) => l.tip === item.v) ?? lines.find((l) => item.v === null || behind(l));
  const newest = target ?? lines[0];
  const ri = [...newest.refs].sort((a, b) => refs[a].rank - refs[b].rank)[0];
  const d = { groups, lines, newest, ri, diverged: lines.length > 1, from: versionCommit(ri, item.mono, newest.tip) };
  if (item.v === newest.tip) return { kind: 'current', ...d };
  if (!target) return { kind: 'ahead', ...d };
  return { kind: item.v === null ? 'add' : 'write', ...d };
}

const report = { written: [], current: 0, divergedCurrent: [], heldLocal: [], heldAhead: [], heldUpstream: [], stale: [] };
let total = 0;

function handle(item) {
  const d = decide(item);
  if (d.kind === 'absent') return;
  total++;
  if (d.kind === 'current') { report.current++; if (d.diverged) report.divergedCurrent.push({ ...item, d }); return; }
  if (d.kind === 'stale') { report.stale.push(item.local); return; }
  if (siteDirty.has(item.local)) { report.heldLocal.push(item.local); return; }
  if (d.kind === 'ahead' && !FORCE.has(item.local)) { report.heldAhead.push({ ...item, d }); return; }
  if (monoDirty.has(item.mono)) { report.heldUpstream.push(item.mono); return; }
  if (!DRY) {
    mkdirSync(dirname(item.dest), { recursive: true });
    writeFileSync(item.dest, blobs.get(d.newest.raw));
  }
  report.written.push({ ...item, d });
}

const readV = (dest) => (existsSync(dest) ? normId(readFileSync(dest)) : null);
const sharedItem = (rel) => ({ local: `src/shared/${rel}`, mono: `shared/${rel}`, dest: join(vendoredShared, rel), v: readV(join(vendoredShared, rel)) });
const rootItem = (name) => ({ local: `scripts/${name}`, mono: name, dest: join(repoRoot, 'scripts', name), v: readV(join(repoRoot, 'scripts', name)) });
/** ./x.mjs imports (static or dynamic) that some monorepo ref has at its root; anything else is the site's own module. */
const importsOf = (buf) => [...buf.toString('utf8').matchAll(/(?:\bfrom\s+|\bimport\s*\(\s*)['"]\.\/([\w.-]+\.mjs)['"]/g)]
  .map((m) => m[1]).filter((name) => trees.some((t) => t.has(name)));

// Every root file this run can reach: the configured ones plus, with followImports, whatever the local copy or any
// ref's version of them imports. Known up front so that all histories come from the one batched fetch below.
function rootCandidates() {
  const out = new Set();
  const q = [...config.rootFiles];
  while (q.length) {
    const name = q.shift();
    if (out.has(name)) continue;
    out.add(name);
    if (!config.followImports) continue;
    const bodies = trees.map((t) => blobs.get(t.get(name))).filter(Boolean);
    if (existsSync(join(repoRoot, 'scripts', name))) bodies.push(readFileSync(join(repoRoot, 'scripts', name)));
    for (const b of bodies) q.push(...importsOf(b));
  }
  return [...out];
}

const sharedItems = vendoredFiles().map(sharedItem);
// Only files that are not simply equal to the one version every ref agrees on need history — usually a handful.
loadHistory([...sharedItems, ...rootCandidates().map(rootItem)]
  .filter((it) => { const g = groupsOf(it.mono); return g.length > 1 || (g.length === 1 && g[0].tip !== it.v); })
  .map((it) => it.mono));

for (const item of sharedItems) handle(item);

// Root files (scripts/<name>.mjs ← monorepo <name>.mjs) and, optionally, the ./x.mjs modules they import — read
// from the copy this repo ends up with, so a held fork keeps its own imports and a refreshed entry brings its new
// helpers.
const queue = [...config.rootFiles];
const seen = new Set();
while (queue.length) {
  const name = queue.shift();
  if (seen.has(name)) continue;
  seen.add(name);
  const item = rootItem(name);
  handle(item);
  if (!config.followImports) continue;
  const written = report.written.find((w) => w.dest === item.dest);
  const body = DRY && written ? blobs.get(written.d.newest.raw) : existsSync(item.dest) ? readFileSync(item.dest) : null;
  if (body) queue.push(...importsOf(body));
}

// Label each HELD-by-(c) file from the same history: which commit, on any branch, carries the vendored content,
// and does it descend from the newest canonical (NEWER) or not (ON ANOTHER BRANCH)?
for (const h of report.heldAhead) {
  const hits = (entries.get(h.mono) || []).filter((e) => e.id && norm(e.id) === h.v);
  if (!hits.length) { h.why = 'none'; continue; }
  h.hit = hits.reduce((a, b) => (b.t > a.t ? b : a));
  h.why = reaches(h.hit.c).has(h.d.from?.c ?? refs[h.d.ri].sha) ? 'newer' : 'branch';
}

// ─── marker ────────────────────────────────────────────────────────────────────────────────────────
const markerText = [
  '# Vendored copy — do not edit',
  '',
  'These files are copies of the monorepo `../shared/` (source of truth for the whole LV ecosystem), taken from',
  'its COMMITTED history (HEAD, its upstream and origin/main), never from its working tree. They are committed',
  'here so GitHub Actions can build this repo standalone, without access to the private parent monorepo.',
  '',
  '`scripts/sync-shared.mjs` refreshes them before every local build/dev. It only ever moves a file FORWARD: a',
  'copy that is newer than, or diverged from, the newest committed canonical is HELD and reported, never reverted.',
  'Edit the monorepo `shared/` instead, commit there, then run `npm run sync:shared` and commit the result here.',
  '',
  'Only the files listed below are vendored, on purpose — this is a refresh, not a mirror. To vendor a new one:',
  '`git -C .. show origin/main:shared/<file> > src/shared/<file>` and commit it.',
  '',
  ...vendoredFiles().sort().map((f) => `- ${f}`),
  '',
  'Generated by `scripts/sync-shared.mjs`.',
  '',
].join('\n');
const markerPath = join(vendoredShared, MARKER);
if (!DRY && existsSync(vendoredShared) && (!existsSync(markerPath) || readFileSync(markerPath, 'utf8') !== markerText)) writeFileSync(markerPath, markerText);

// ─── report ────────────────────────────────────────────────────────────────────────────────────────
const refLabel = (ri) => refs[ri].name;
const sources = refs.map((r) => `${r.labels.join(' = ')} ${short(r.sha)}`).join(' · ');
const origin = (d) => `${refLabel(d.ri)} ${d.from ? `${short(d.from.c)} (${date(d.from.t)})` : short(refs[d.ri].sha)}`;
const others = (d) => d.lines.filter((l) => l !== d.newest).map((l) => l.refs.map(refLabel).join(' = ')).join(', ');
const disagree = (d) => (d.diverged
  ? `  (refs disagree: ${others(d)} ${d.lines.length > 2 ? 'have' : 'has'} a different version)`
  : '');

if (report.written.length) {
  console.log(`${TAG} ${DRY ? 'Would refresh' : 'Refreshed'} ${report.written.length}/${total} vendored file(s) from the monorepo${DRY ? '' : ' — commit them so CI builds the same code'}:`);
  for (const w of report.written) console.log(`  • ${w.local}  ← ${origin(w.d)}${w.v === null ? ' (added)' : ''}${FORCE.has(w.local) && w.d.kind === 'ahead' ? ' (--force)' : ''}${disagree(w.d)}`);
}
console.log(`${TAG} ${report.current}/${total} vendored file(s) current with the newest committed monorepo version (${sources}).`);
if (report.divergedCurrent.length) {
  console.log(`${TAG} Note: ${report.divergedCurrent.length} of them match one source ref while another has a different version (the refs diverged on these files; merging the branches upstream reconciles them):`);
  for (const c of report.divergedCurrent) console.log(`  • ${c.local} — matches ${refLabel(c.d.ri)}; ${others(c.d)} ${c.d.lines.length > 2 ? 'have' : 'has'} another version`);
}
if (report.heldAhead.length) {
  console.warn(`${TAG} HELD ${report.heldAhead.length} file(s) — not behind the newest committed monorepo version, so a refresh would move them backwards or sideways:`);
  for (const h of report.heldAhead) {
    const newest = origin(h.d);
    if (h.why === 'newer') console.warn(`  • ${h.local} — NEWER than ${newest}: matches monorepo commit ${short(h.hit.c)} (${date(h.hit.t)}) "${h.hit.s}"`);
    else if (h.why === 'branch') console.warn(`  • ${h.local} — ON ANOTHER BRANCH: matches monorepo commit ${short(h.hit.c)} (${date(h.hit.t)}) "${h.hit.s}", which is not in ${refLabel(h.d.ri)}'s history; newest canonical: ${newest}`);
    else console.warn(`  • ${h.local} — NO MONOREPO COMMIT has this content (patched in place or edited by hand); newest canonical: ${newest}`);
  }
  console.warn(`${TAG} Adopt the canonical for a held file on purpose, once nothing in it would be lost: node scripts/sync-shared.mjs --force ${report.heldAhead[0].local}`);
}
if (report.heldLocal.length) {
  console.warn(`${TAG} HELD ${report.heldLocal.length} file(s) uncommitted in this repo — left alone so that work is not destroyed; commit or discard, then re-run:`);
  for (const f of report.heldLocal) console.warn(`  • ${f}`);
}
if (report.heldUpstream.length) {
  console.warn(`${TAG} HELD ${report.heldUpstream.length} file(s) with uncommitted changes in the monorepo — not synced until they are committed there:`);
  for (const f of report.heldUpstream) console.warn(`  • ../${f}`);
}
if (report.stale.length) {
  console.warn(`${TAG} STALE ${report.stale.length} vendored file(s) exist in no monorepo ref (renamed or deleted upstream?) — left in place:`);
  for (const f of report.stale) console.warn(`  • ${f}`);
}
