// Generated by scripts/og/gen_page_cards.mjs from scripts/og/page-function-template.js — do not edit by hand
// (scripts/og/audit.mjs compares this file byte-for-byte on every site that has page cards).
//
// Serves the seasonal PAGE share card at /og/<slug>.jpg: <slug>-summer.jpg May–Sep, <slug>-winter.jpg
// Oct–Apr. Sama sääntö kuin sivustokortin /og.jpg-funktiolla ja kuin sivujen oma runtime-seasonal(),
// jotta WhatsAppin, Facebookin ja LinkedInin esikatselu näyttää sen kuvan johon kävijä oikeasti laskeutuu.
//
// 🔴 Vesa 21.9.2026: *"jokainen tarvitsee sen kesä jakokuvan sekä talvijakokuvan"*. Ensimmäinen versio
// sivukorteista teki yhden kiinteän kortin per sivu, ja se olisi näyttänyt lumista tunturia keskellä
// heinäkuuta — juuri se vika, jonka takia sivustokortti tehtiin kausikohtaiseksi 6.9.
//
// 🔴 Reitti on /og/<slug>.jpg ja staattiset tiedostot ovat /og/<slug>-summer.jpg ja -winter.jpg: Pages
// valitsee staattisen tiedoston ennen funktiota, joten funktion polku EI saa olla minkään staattisen
// tiedoston niminen. Sama syy kuin sivustokortilla, jossa funktio on /og.jpg ja tiedostot og-summer.jpg.
//
// Mikä tahansa virhe putoaa talvikorttiin ja sitten sivustokorttiin, joten pahin tapaus on vanha
// käytös, ei koskaan 500.
export async function onRequest({ request, params, env }) {
  const url = new URL(request.url);
  const slug = String(params.card || '').replace(/\.jpg$/i, '').replace(/[^a-z0-9-]/gi, '');
  if (!slug) return new Response('Share card not found', { status: 404 });
  // 🔴 Funktio nappaa KAIKEN /og/-polun alta, myös suorat `-summer.jpg` / `-winter.jpg`.
  // Ilman tätä haaraa suora linkki talvikorttiin palautti og-defaultin (mitattu livenä
  // 21.9.: X-LV-OG-Season: fallback) — eli väärän kuvan ilman mitään virhettä. Kausitiedosto
  // tarjoillaan sellaisenaan; vain kaudeton nimi valitsee kauden.
  const suora = slug.match(/-(summer|winter)$/);
  if (suora) {
    const res = await env.ASSETS.fetch(new Request(`${url.origin}/og/${slug}.jpg`, { method: 'GET' }));
    if (!res.ok) return new Response('Share card not found', { status: 404 });
    const headers = new Headers(res.headers);
    headers.set('Content-Type', 'image/jpeg');
    headers.set('Cache-Control', 'public, max-age=86400');
    headers.set('X-LV-OG-Season', suora[1]);
    return new Response(res.body, { status: 200, headers });
  }
  const month = new Date().getUTCMonth() + 1;
  const season = month >= 5 && month <= 9 ? 'summer' : 'winter';
  const toinen = season === 'summer' ? 'winter' : 'summer';
  for (const name of [`/og/${slug}-${season}.jpg`, `/og/${slug}-${toinen}.jpg`, '/og-default.jpg']) {
    try {
      const res = await env.ASSETS.fetch(new Request(url.origin + name, { method: 'GET' }));
      if (!res.ok) continue;
      const headers = new Headers(res.headers);
      headers.set('Content-Type', 'image/jpeg');
      headers.set('Cache-Control', 'public, max-age=86400');
      headers.set('X-LV-OG-Season', name === '/og-default.jpg' ? 'fallback' : name.endsWith(`-${season}.jpg`) ? season : `${toinen}-only`);
      return new Response(res.body, { status: 200, headers });
    } catch (_) { /* seuraava ehdokas */ }
  }
  return new Response('Share card not found', { status: 404 });
}
