// Generated by scripts/gyg-wire-images.mjs — do not edit by hand.
//
// Card images for the GetYourGuide picks, keyed by the product path so a card
// and its image can never drift apart. AI-generated with Picsart (gpt-image-2)
// on 2026-07-30; GetYourGuide's own photos are NOT used, they belong to the
// operators. One image is used on exactly one ecosystem site.
import img0 from '../assets/gyg/daytime-husky-safari.webp';
import img1 from '../assets/gyg/snowmobile-northern-lights-hunting-trip.webp';
import img2 from '../assets/gyg/ranua-s-wildlife-park-ticket-with-transportati.webp';
import img3 from '../assets/gyg/icebreaker-arktis-cruise-with-ice-floating.webp';

export const GYG_IMAGES: Record<string, string> = {
  'rovaniemi-l2653/rovaniemi-daytime-husky-safari-t437502': img0,
  'sirkka-l139331/levi-snowmobile-northern-lights-hunting-trip-t407158': img1,
  'rovaniemi-l2653/rovaniemi-ranua-s-wildlife-park-ticket-with-transportation-t786889': img2,
  'kemi-l98127/kemi-icebreaker-arktis-cruise-with-ice-floating-t727384': img3,
};
